// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMDHRXpSfgp8zVoq73GZK743Xgy8b89E',
    appId: '1:246309298185:android:4a14dff3ff45e2c21518d8',
    messagingSenderId: '246309298185',
    projectId: 'garbagemana',
    storageBucket: 'garbagemana.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyUGdCbyP3ySA5VlY04dridFvPc32sQQ',
    appId: '1:246309298185:web:2c03d9259cdab2831518d8',
    messagingSenderId: '246309298185',
    projectId: 'garbagemana',
    authDomain: 'garbagemana.firebaseapp.com',
    storageBucket: 'garbagemana.appspot.com',
    measurementId: 'G-42XRK0DJ40',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPyUGdCbyP3ySA5VlY04dridFvPc32sQQ',
    appId: '1:246309298185:web:e291582b8969d35d1518d8',
    messagingSenderId: '246309298185',
    projectId: 'garbagemana',
    authDomain: 'garbagemana.firebaseapp.com',
    storageBucket: 'garbagemana.appspot.com',
    measurementId: 'G-72C5SHMCV0',
  );

}